update screenshot on success 2

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -1,30 +1,25 @@
-name: Java Playwright CI
+name: Deploy Reports to GitHub Pages
 
 on:
   push:
     branches:
-      - main
-  pull_request:
-    branches:
-      - main
+      - main  # Trigger on changes to the main branch
 
 jobs:
   run-tests:
-    name: Run Playwright Tests
+    name: Run Tests
     runs-on: ubuntu-latest
-    continue-on-error: true
-
     steps:
-      - name: Checkout code
+      - name: Checkout Code
         uses: actions/checkout@v3
 
-      - name: Set up JDK
+      - name: Set up Java
         uses: actions/setup-java@v3
         with:
           java-version: '17'
           distribution: 'temurin'
 
-      - name: Cache Maven packages
+      - name: Cache Maven Packages
         uses: actions/cache@v3
         with:
           path: ~/.m2
@@ -32,41 +27,38 @@ jobs:
           restore-keys: |
             ${{ runner.os }}-m2
 
-      - name: Install Maven dependencies
+      - name: Install Dependencies
         run: mvn install -DskipTests
 
-      - name: Start Xvfb
-        run: |
-          sudo apt-get update
-          sudo apt-get install -y xvfb
-          Xvfb :99 -screen 0 1920x1080x16 &
+      - name: Run Tests
+        run: mvn test || echo "Tests failed but continuing."
 
-      - name: Export DISPLAY variable
-        run: echo "DISPLAY=:99" >> $GITHUB_ENV
-
-      - name: Run tests
-        run: mvn test || echo "Tests failed, but continuing with the workflow."
-
-      - name: Archive test results
+      - name: Archive Test Reports
         uses: actions/upload-artifact@v3
         with:
-          name: Playwright-Test-Reports
+          name: Test-Reports
           path: Reports/
 
   deploy-pages:
-    name: Deploy to GitHub Pages
+    name: Deploy Reports to GitHub Pages
     runs-on: ubuntu-latest
+    needs: run-tests
     permissions:
       contents: write
-    needs: run-tests
     if: always()
 
     steps:
-      - name: Checkout code
+      - name: Checkout Code
         uses: actions/checkout@v3
 
-      - name: Deploy Reports to GitHub Pages
+      - name: Download Test Reports
+        uses: actions/download-artifact@v3
+        with:
+          name: Test-Reports
+
+      - name: Deploy to GitHub Pages
         uses: peaceiris/actions-gh-pages@v3
         with:
           github_token: ${{ secrets.PERSONAL_ACCESS_TOKEN  }}
           publish_dir: Reports/
+          force_orphan: true  # Create a new commit every time
